server:
  port: 8090
  context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://watchacha.ckhnav7yzn73.ap-northeast-2.rds.amazonaws.com
    username: admin
    password: koreait1234
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: C:/springImg

  mail:
    host: smtp.gmail.com
    port: 587
    username: johyeonmin841@gmail.com
    password: zpjvoilqpcorlnmu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "875919437056-rh3np19943os9vpii98crn4hqkd274sh.apps.googleusercontent.com"
            client-secret: "5V4De6a79E0PfW2Aa_DQLMtp"
            scope:
              - email
              - profile

          facebook:
            client-id: 248745953463459
            client-secret: 54030a23563e5247ec031b2c908ef40e
            scope:
              - email
              - public_profile
          naver:
            client-id: LDxu3BhL6x4w704G_x3a
            client-secret: cCMi8kjLld
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/naver
          kakao:
            authorization-grant-type: authorization_code
            client-id: 1f9b7d27e220f586c38fd2f97902d30b
            client-secret: LBJjQrTEjYWd9UDpeQBuYcpIkC89PyIU
            redirect-uri: http://localhost:8090/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해준다.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties




mybatis: # mybatis
  mapper-locations: mybatis-mapper/**/*.xml # resources 폴더 아래에 mybatis-mapper 폴더 안에 폴더수 상관없이 xml파일은 전부
  type-aliases-package: com.spring.wachacha # parameter type 또는 Result Type 에 클래스명만 적으면 이 경로 아래에서 그 클래스(게터세터 있는)를 찾아준다.

google:
  recaptcha:
    key:
      site: 6Lf-IYQbAAAAAGNjne1KZ2lqMRe9KC_xw1pOVPlo
      secret: 6Lf-IYQbAAAAADJZj_62RLCH0DULZ3hl3NV9f_EH
      url: https://www.google.com/recaptcha/api/siteverify